spring:
  banner:
    charset: UTF-8
  application:
    name: springboot-transactional
  datasource:
    url: jdbc:mysql://localhost:3306/loiter?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-betwwen-eviction-runs-millis: 60000
    mi-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-preared-statement-per-connection-size: 20
    filters: stat, wall
    use-global-data-source-stat: true
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

server:
  port: 8080

#logging:
#  config: classpath:spring-logback.xml
#  pattern:
#    console: "%d - %msg%n"
#  level: info