server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:27706/shirodemo?autoReconnect=true&useUnicode=true&useAffectedRows=true&characterEncoding=utf8
    username: root
    password: doctor330_2016Brenda
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      charset: utf-8
      enabled: true
# 配置slq打印日志
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl